### ISSUE TITLE
Is there a .jar file?

### ISSUE THREAD

**Issue by Exlsunshine** [worker8/TourGuide#12]
Hi, this library is remarkable, but I am using eclipse now, and I wonder how to use it in eclipse?
Is there a .jar library file?

Thank you.

**Comment by worker8** [comment]
Thanks, but it will not be supported in near future. This cannot be an .jar and it must be an .aar because it uses some graphics assets. 

I tried to make it work, but I'm facing issue with the dependencies of TourGuide, for example: floating action button.

Since most people will be using Android Studio now, I will not spend too much time on this for now as there are many other open issues. Sorry. :(

**Comment by Exlsunshine** [comment]
Never mind, I build a project for eclipse.
It's right here https://github.com/Exlsunshine/TourGuide. But due to this
is used for eclipse, so I can't fork it from your repository and propose a
pull request, so I have to copy your code and make some change then put it
in a new repository, I mention about your work in the readme.md file.

Many thanks to your amazing project, it really helps me a lot!

2015-08-17 14:17 GMT+08:00 Tan Jun Rong notifications@github.com:
