### ISSUE TITLE
Overlay not cleaning up

### ISSUE THREAD

**Issue by kalpeshdeo** [worker8/TourGuide#2]
When i click in the target button, overlay should close. but its not. Its still showing the overlay on the next screen.

**Comment by worker8** [comment]
Did you call `mTourGuideHandler.cleanUp();`?

You need to call it inside the button's `OnClickListener`.

**Comment by kalpeshdeo** [comment]
ohh, its not a straight forward then :( . bcz showing overlay is at different place and clicklisterner is at other place. I need to maintain object of TourGuide.
Actually it should be close by library it self. You can refer Showcaseview.

**Comment by worker8** [comment]
It's actually a good idea to have this feature. However, I think it's hard to be done without the use of [Reflection](https://docs.oracle.com/javase/tutorial/reflect/).

I took a look at [ShowcaseView](https://github.com/amlcurran/ShowcaseView), I noticed that it is able to close itself when you click on the button on the overlay, but **not** able to close itself when you click on the button that is `playOn()` without calling `showcaseView.hide();` explicitly, which is similar in TourGuide. 

In order to be able to make a `playOn` button close itself, I'll need to be able to intercept the `onClickListener` of a `View`. So that we can do this:

```
        @Override
        public void onClick(View view) {
            // Run code to close TourGuide
            /* User's original onClickListener code runs here */
        }
```

I checked the `mOnClickListener` of an `android.view.View`, it's not accessible even by extending it. The only way I found out to obtain `mOnClickListener` is through the use of Reflection:
http://stackoverflow.com/a/14993764/75579 . But the Author of the answer did warn that it will break if the internal structure of View changes. So I'm hesitant to add this feature.

I'll be closing this unless you can find a better way to get `mOnClickListener` from `android.view.View`.

You can reopen this if you have new findings. Thanks

**Comment by saket** [comment]
You can always call `mButton.performClick()`

**Comment by tasn** [comment]
Hey,

I've also encountered the same issue, and manually hiding is cumbersome. I understand there's no easy solution to making it clean and automatic. What I decided to do instead is to disable the click through the hole, and make a click on the pointer release the tourguide. However, there's no way to set a click listener on the pointer, so even this doesn't work.

I wonder, two years later, what is the recommended solution for this issue, and is it possible to maybe add a click listener to the pointer view and make it the recommended solution?

The problem I have, and I assume what the others in this thread meant, is that we want to isolate the tourguide code in the tourguide, it feels dirty to have the rest of the code aware of the tourguide, instead of encapsulating all of the tourguide related code in the tour guide itself. This is why adding a click listener on the pointer, and simulating a click on the "play on" object feels cleaner.

Thanks.
