### ISSUE TITLE
Is it possible to display TourGuide on AlertDialog 

### ISSUE THREAD

**Issue by drdesai03** [worker8/TourGuide#38]
Hi, I am preparing one demo application for I am using this library for guiding. 
In my App I also want user to have look at alert dialog So I want tourGuide on Alert Dialog. 

Can you help me how do I archive this.? 

I am trying the same code but it show behind alert dialog.

**Comment by worker8** [comment]
Hi @drdesai03, sadly, it is currently not possible :(

@aaronliew is currently working on a fix for this. But we only get to work on this part time, so hopefully it's up in the next 2 weeks.

Since this is a commonly asked question, I added this to limitations document so that others can refer to it too: [Limitations](https://github.com/worker8/TourGuide/wiki/Limitations)

**Comment by zeroarst** [comment]
I have cloned the repository and made it working with DialogFragment.
Not sure how to do pull request...

![image](https://user-images.githubusercontent.com/1834837/36845097-2025c150-1da1-11e8-8630-68ee449d4212.png)
