### ISSUE TITLE
Major memory leak.

### ISSUE THREAD

**Issue by MHDante** [worker8/TourGuide#4]
The overlay bitmap seems to be leaking. Perhaps from the canvas reference? I'll look into it.

**Comment by MHDante** [comment]
To test, Launch the demo app while an overlay is on and turn the phone over and over. 
Alternatively, launch demo app and select a demo, press back, select a demo, etc. 
Memory use skyrockets and app crashes due to OOM exception.
:S

**Comment by worker8** [comment]
Thanks for the finding. Can confirm, this is really bad. I will also look for the cause for this. Let me know if you can find the root cause or solution for this.

Here's the memory usage graph when I launch demo app, then select demo and press back repeatedly:
![memory leak graph](http://i.imgur.com/mvZxfED.png)

**Comment by MHDante** [comment]
I fixed it.
Pull request incoming.
Thank you for contributing to Open source! <3
