### ISSUE TITLE
Customize Overlay background

### ISSUE THREAD

**Issue by Tomasu** [worker8/TourGuide#57]
I'd like to be able to customize the Overlay's background, for instance to not have a hole but still tint.

**Comment by worker8** [comment]
Thanks for using the library.

> not have a hole but still tint

What I imagine it will be like this:

![](http://i.imgur.com/C47hbeu.png)

I'm not sure what is the use case for this, I thought it will always be better if we use the hole because this way, users can easily tell which button they need to look at. Can you describe your use case?

I do understand that sometimes the button is too long, and the hole became ridiculously big, is that the case?

If it is, I think a feature to control the size of the radius will be better.

**Comment by Tomasu** [comment]
In my case, I actually wanted to have a tooltip that explained something but didn't apply to a specific element. You could also say it'd apply to the whole screen in a way, but the designers require it to tint the whole screen. setting the radius to 0 would be fine :)

**Comment by Tomasu** [comment]
Ok, a little research says that the widthPixels and heightPixels of DisplayMetrics does NOT return the raw device screen size.

**Comment by worker8** [comment]
I implemented a new feature to let `Overlay` configure radius, check out this commit: https://github.com/worker8/TourGuide/commit/72f3e8240e595ffcfd32e7a117a8acd63c7ad510

Here is a sample of how to use it:

```
mTutorialHandler = TourGuide.init(this).with(TourGuide.Technique.Click)
            .setPointer(pointer)
            .setToolTip(toolTip)
            .setOverlay(new Overlay().setBackgroundColor(Color.parseColor("#66FF0000")).setHoleRadius(0))
            .playOn(button);
```

I think this will solve your issue. I'm closing this issue for now, reopen if there is still something wrong.

Hope it helps! :)
